doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            BoltSeo:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/vendor/appolodev/bolt-seo/src'
                prefix: 'Appolo\BoltSeo'
                alias: BoltSeo

framework:
    translator:
        paths: ['%kernel.project_dir%/vendor/appolodev/bolt-seo/translations']
